name: Update dlp

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/opensuse/leap:15.5
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      run: >
        zypper -n install tar gzip make gcc
        'perl(Algorithm::Diff)'
        'perl(Archive::Zip)'
        'perl(Class::Accessor::Chained)'
        'perl(File::ShareDir::Install)'
        'perl(LWP::UserAgent)'
        'perl(Module::Build)'
        'perl(Module::Build::Tiny)'
        'perl(Parse::CPAN::Packages)'
        'perl(Perl::PrereqScanner)'
        'perl(Pod::POM)'
        'perl(Text::Autoformat)'
        'perl(YAML::XS)'
        'perl(XML::Simple)'
        obs-service-format_spec_file
        procmail
        wget
        osc

      # procmail for /usr/bin/lockfile

    - name: test
      run: |
        bin/fetch-cpan.sh
        ls -lrt ~/obs-mirror
        ls -lrt ~/obs-mirror/cpan

    - name: status
      run: |
        ./bin/status-perl --data ~/obs-mirror --project home:tinita:testautoupdate --update


    - name: update
      run: |
        ./bin/update-perl \
            --data ~/obs-mirror \
            --project home:tinita:testautoupdate \
            --max 1

